//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asistencias
    {
        public int idAsistencia { get; set; }
        public int idEstudiante { get; set; }
        public int idGrupo { get; set; }
        public System.DateTime fecha { get; set; }
        public int idTipoAsistencia { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
        public virtual Grupos Grupos { get; set; }
        public virtual TiposAsistencia TiposAsistencia { get; set; }
    }
}
