//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grupos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Grupos()
        {
            this.Asistencias = new HashSet<Asistencias>();
            this.LineasMatricula = new HashSet<LineasMatricula>();
        }
    
        public int idGrupo { get; set; }
        public int idProfesor { get; set; }
        public int Numero { get; set; }
        public int idCurso { get; set; }
        public int idPeriodo { get; set; }
        public int idHorario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Asistencias> Asistencias { get; set; }
        public virtual Cursos Cursos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LineasMatricula> LineasMatricula { get; set; }
        public virtual Horarios Horarios { get; set; }
        public virtual Periodos Periodos { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
